on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: test action
        id: test
        uses: takenorio/action-test@da30a65386e0d4d3e885c96a6642d7763c2ece77
        with:
          id_of_input: 'input value'
      - name: view result
        run: |
          echo ${{ env.id_of_output }}
        env:
          id_of_output: ${{ steps.test.outputs.id_of_output }}
